name: z - Check MATLAB Release

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    name: Check MATLAB Release
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v3
      
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: Statistics_and_Machine_Learning_Toolbox

      # Check for MATLAB code issues in the project.
      - name: Show MATLAB Release
        uses: matlab-actions/run-command@v2
        if: always()
        with:
          command: addpath(pwd);addpath('tests');results = runtests('testSmoke.m')
          #command: ver; mydir=pwd;disp(mydir); ls;b=dataset();disp(b)

      # Run tests
      #- name: Run tests and generate artifacts
      #  uses: matlab-actions/run-tests@v2
      #  with:
      #    test-results-junit: test-results/results.xml
      #    logging-level: detailed
